plugins {
    id 'application'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.18.2'
    configFile = file("config/checkstyle/checkstyle.xml")
}

repositories {
    mavenCentral()
}

def gdxVersion = "1.13.1"

dependencies {
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation 'com.google.code.gson:gson:2.11.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['assets']
        }
    }
}

application {
    mainClass = 'DesktopLauncher'
}

run {
    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        def iconFile = file('assets/images/ui/icon.png')

        if (iconFile.exists()) {
            jvmArgs '-XstartOnFirstThread',
                    "-Xdock:icon=${iconFile.absolutePath}",
                    '-Xdock:name=Plants vs Zombies'
        } else {
            jvmArgs '-XstartOnFirstThread',
                    '-Xdock:name=Plants vs Zombies'
        }
    }
}