plugins {
    id 'application'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.18.2'
    configFile = file("config/checkstyle/checkstyle.xml")
}

repositories {
    mavenCentral()
}

def gdxVersion = "1.13.1"

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'

    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'

    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-maps:$gdxVersion"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

application {
    mainClass = 'Main'
}

tasks.named('test') {
    useJUnitPlatform()
}